export const ACTION_WINDOW_RESIZE = "ACTION_WINDOW_RESIZE";
export const ACTION_USER_LOGIN = "ACTION_USER_LOGIN";
export const ACTION_USER_LOGOUT = "ACTION_USER_LOGOUT";

export const ACTION_CHAT_SERVER_PUSH = "ACTION_CHAT_SERVER_PUSH";//服务端主动推送
export const ACTION_CHAT_CONNECTED = "ACTION_CHAT_CONNECTED";//用户建立链接
export const ACTION_CHAT_DISCONNECTED = "ACTION_CHAT_DISCONNECTED";//用户断开了连接
export const ACTION_CHAT_LOGIN = "ACTION_CHAT_LOGIN";//用户登录
export const ACTION_CHAT_ENTER_ROOM = "ACTION_CHAT_ENTER_ROOM";//进入房间





