export const MUTATION_WINDOW_RESIZE = "MUTATION_WINDOW_RESIZE";
export const MUTATION_USER_LOGIN = "MUTATION_USER_LOGIN";
export const MUTATION_USER_LOGOUT = "MUTATION_USER_LOGOUT";

export const MUTATION_CHAT_CONNECTED = "MUTATION_CHAT_CONNECTED";
export const MUTATION_CHAT_DISCONNECTED = "MUTATION_CHAT_DISCONNECTED";
export const MUTATION_CHAT_LOGIN = "MUTATION_CHAT_LOGIN";
export const MUTATION_CHAT_ROOM_SET = "MUTATION_CHAT_ROOM_SET";
export const MUTATION_CHAT_APPEND_MESSAGE = "MUTATION_CHAT_APPEND_MESSAGE";
